"use client";

import { useState } from "react";
import { Activity, Stethoscope, Lightbulb, Download, X, Users, Check } from "lucide-react";
import { generateHealthPDF } from "@/lib/generatePDF";

export interface HealthSummaryData {
  primary_symptom: string;
  possible_causes: string;
  recommended_action: string;
  severity: "green" | "yellow" | "red" | string;
}

interface HealthSummaryProps {
  summary: HealthSummaryData;
  onClose?: () => void;
  familyMemberId?: string;
  familyMemberName?: string;
  familyMemberRelation?: string;
}

const SECTION_CONFIG: {
  key: keyof Omit<HealthSummaryData, "severity">;
  label: string;
  icon: React.ReactNode;
}[] = [
  {
    key: "primary_symptom",
    label: "Primary Symptom",
    icon: <Activity className="w-4 h-4 text-blue-500" strokeWidth={2.5} />,
  },
  {
    key: "possible_causes",
    label: "Possible Causes",
    icon: <Stethoscope className="w-4 h-4 text-emerald-500" strokeWidth={2.5} />,
  },
  {
    key: "recommended_action",
    label: "Recommended Action",
    icon: <Lightbulb className="w-4 h-4 text-amber-500" strokeWidth={2.5} />,
  },
];

export default function HealthSummary({
  summary,
  onClose,
  familyMemberName,
  familyMemberRelation,
}: HealthSummaryProps) {
  const [downloading, setDownloading] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  const handleDownloadPDF = async () => {
    setDownloading(true);
    try {
      await generateHealthPDF({
        patient: familyMemberName
          ? { name: familyMemberName, relation: familyMemberRelation }
          : undefined,
        history: [
          {
            date: new Date().toISOString(),
            symptom_query: summary.primary_symptom,
            ai_response: `Possible Causes:\n${summary.possible_causes}\n\nRecommended Action:\n${summary.recommended_action}`,
            severity: summary.severity,
          },
        ],
        filename: `sahayak-health-summary-${Date.now()}.pdf`,
      });
      setDownloadSuccess(true);
      setTimeout(() => setDownloadSuccess(false), 3000);
    } catch (err) {
      console.error("PDF generation failed:", err);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="w-full bg-white dark:bg-slate-900 border-2 border-gray-100 dark:border-gray-800 rounded-lg overflow-hidden animate-msg-in">
      <div className="bg-blue-500 px-5 py-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded bg-white/20 flex items-center justify-center text-white">
            <Activity className="w-4 h-4" strokeWidth={2.5} />
          </div>
          <div>
            <h3 className="text-sm font-extrabold text-white leading-tight">
              Health Summary
            </h3>
            {familyMemberName && (
              <p className="text-[10px] text-blue-100 font-medium">
                For {familyMemberName} ({familyMemberRelation})
              </p>
            )}
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleDownloadPDF}
            disabled={downloading}
            className="inline-flex items-center gap-1.5 bg-white hover:bg-gray-100 text-blue-600 text-xs font-bold px-3 py-1.5 rounded-md transition-all duration-200 hover:scale-105 disabled:opacity-60"
          >
            {downloadSuccess ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-500" />
                <span>Saved PDF</span>
              </>
            ) : (
              <>
                <Download className="w-3.5 h-3.5" />
                <span>{downloading ? "Generating..." : "Download PDF"}</span>
              </>
            )}
          </button>
          {onClose && (
            <button
              onClick={onClose}
              className="text-white/80 hover:text-white p-1 rounded-md transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      <div className="divide-y-2 divide-gray-100 dark:divide-gray-800">
        {SECTION_CONFIG.map(({ key, label, icon }) => (
          <div key={key} className="p-4 space-y-1">
            <div className="flex items-center gap-2 mb-1">
              {icon}
              <span className="text-xs font-bold text-gray-400 dark:text-gray-500 uppercase tracking-widest">
                {label}
              </span>
            </div>
            <p className="text-xs font-semibold text-gray-900 dark:text-white leading-relaxed pl-6">
              {summary[key]}
            </p>
          </div>
        ))}
      </div>

      <div className="px-4 py-3 bg-gray-50 dark:bg-slate-800 border-t-2 border-gray-100 dark:border-gray-800 flex flex-col gap-2">
        <p className="text-[10px] text-gray-400 dark:text-slate-400 text-center font-medium">
          Informational summary generated by Sahayak Health AI. Always consult a medical professional.
        </p>
      </div>
    </div>
  );
}
